Library Management System/Models/issuebook.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuebook
    {
        public int id { get; set; }
        public Nullable<int> m_id { get; set; }
        public string book_id { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
    }
}

Library Management System/Controllers/IssueBookController.cs
using Lib2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lib2.Controllers
{
    public class IssueBookController : Controller
    {
        // GET: IssueBook
        private lib1Entities1 db = new lib1Entities1();
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult GetBook()
        {
            var books = db.books.Select(p => new
            {
                ID=p.id,
                Bname=p.bname
            }).ToList();
            return Json(books, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Save(issuebook issue)
        {
            if (ModelState.IsValid)
            {

                db.issuebooks.Add(issue);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(issue);
        }

        [HttpPost]
        public ActionResult GetMid(int m_id)
        {
            var memberid = (from s in db.members where s.id == m_id select s.name).ToList();
            return Json(memberid, JsonRequestBehavior.AllowGet);
        }
        
    }
}

Library Management System/Views/IssueBook/Index.cshtml
<div class="row">
    <div class="col-sm-4">
        @using (Html.BeginForm("Save", "IssueBook", FormMethod.Post))
        {
            <h3>
                Issue Book
            </h3>

            <div class="form-group">
                <label>Member ID</label>
                <input type="text" id="m_id" name="m_id" class="form-control" placeholder="Member ID" required />
            </div>

            <div class="form-group">
                <label>Member name</label>
                <input type="text" id="mname" name="mname" class="form-control" placeholder="Member name" required />
            </div>

            <div class="form-group">
                <label>Book</label>
                <select id="book_id" name="book_id" class="form-control">
                    <option>Please Select</option>
                </select>
            </div>


            <div class="form-group">
                <label>Issue Date</label>
                <input type="date" id="issuedate" name="issuedate" class="form-control" required />
            </div>

            <div class="form-group">
                <label>Return Date</label>
                <input type="date" id="returndate" name="returndate" class="form-control" required />
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" required />
            </div>

        }


    </div>
</div>
@section scripts{

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

    <script>
        getMid();
       getBook();
        function getMid() {

            console.log("hello from getm_id")
            $("#m_id").keyup(function (e) {

                $.ajax({
                    type: 'POST',
                    url: '/IssueBook/GetMid?m_id=' + $("#m_id").val(),
                    dataType: 'JSON',
                    success: function (data) {
                        $("#mname").val(data)

                    }

                });
            });
        };
        function getBook() {
            $("#m_id").keyup(function (e) {

                $.ajax({
                    type: 'GET',
                    url: '/IssueBook/GetBook',
                    dataType: 'JSON',
                    success: function (data) {

                        for (var i = 0; i < data.length; i++) {
                            $("#book_id").append($("<option/>", {
                                text: data[i].Bname
                            }));
                        }


                    }
                });
            })
        };
    </script>

}